version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: relmn-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: relmn-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      - mongo
    restart: unless-stopped
volumes:
  mongo-data:
